from .regression_scaffold.regression_scaffold import RegressionScaffold
from .classification_scaffold.vanilla_classification_scaffold import VanillaClassificationScaffold as ImageClassificationScaffold
